# Generated by Django 4.2.1 on 2023-10-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0022_recurring_bills_amt_paid_recurring_bills_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebills',
            name='customer_gst_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
