# Generated by Django 4.2.1 on 2023-10-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0023_purchasebills_customer_gst_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebills',
            name='amt_paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasebills',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasebills',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebills',
            name='repeat_every',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
