# Generated by Django 4.2.1 on 2023-10-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0024_purchasebills_amt_paid_purchasebills_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebills',
            name='customer_gst_no',
        ),
        migrations.AddField(
            model_name='purchasebillitems',
            name='hsn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
