# Generated by Django 4.2.1 on 2023-10-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0025_remove_purchasebills_customer_gst_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebills',
            name='adjustment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
