# Generated by Django 4.2.1 on 2023-10-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0027_purchasebillitems_user_purchase_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebills',
            name='discount',
        ),
        migrations.AddField(
            model_name='purchasebillitems',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
